# Generated by Django 4.2 on 2023-07-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0005_property_is_featured'),
        ('negotiation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property_form.property'),
            preserve_default=False,
        ),
    ]
