# Generated by Django 4.2 on 2023-07-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0002_negotiation_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
