# Generated by Django 2.2.28 on 2023-08-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0004_auto_20230804_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
