# Generated by Django 4.2.4 on 2023-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0006_alter_negotiation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='requested_price',
            field=models.IntegerField(),
        ),
    ]
