# Generated by Django 4.2.4 on 2023-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0008_alter_negotiation_requested_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='requested_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
