# Generated by Django 4.2 on 2023-07-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
    ]
