# Generated by Django 4.2 on 2023-05-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('square_feet', models.PositiveIntegerField()),
                ('overview', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pictures', models.ImageField(upload_to='property_pictures/')),
                ('nearby_police_stations', models.ManyToManyField(related_name='properties', to='property_form.policestation')),
                ('nearby_schools', models.ManyToManyField(related_name='properties', to='property_form.school')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.seller')),
            ],
        ),
    ]
