# Generated by Django 4.2 on 2023-05-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
