# Generated by Django 4.2 on 2023-05-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0002_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
    ]
