# Generated by Django 4.2.1 on 2023-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0003_alter_property_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='nearby_police_stations',
        ),
        migrations.AddField(
            model_name='property',
            name='bhk',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_hospitals',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_police_station',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='property',
            name='nearby_schools',
        ),
        migrations.AlterField(
            model_name='property',
            name='pictures',
            field=models.ImageField(upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='PoliceStation',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_schools',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
