# Generated by Django 4.2 on 2023-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0004_remove_property_nearby_police_stations_property_bhk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
