# Generated by Django 4.2.1 on 2023-08-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0006_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
    ]
