# Generated by Django 2.2.28 on 2023-08-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0009_auto_20230805_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
