# Generated by Django 4.2.4 on 2023-08-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0010_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
