# Generated by Django 4.2.4 on 2023-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_form', '0011_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(),
        ),
    ]
